customer_portal/urls.py
from rest_framework import routers
from django.conf import settings
from django.conf.urls.static import static,serve
from django.contrib import admin
from django.urls import path,include
import django.views.static
from project import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'awards', views.AwardsViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('project.urls')),
    path('api', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

] 

if settings.DEBUG == True:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from . import views
from .views import *
from .forms import *

app_name = 'project'

urlpatterns = [
	path('',auth_views.LoginView.as_view(template_name='project/login.html',redirect_authenticated_user=True),name='no_page'),
	path('register/',views.register,name='register'),
	path('index/',views.index,name='index'),
	path('login/', auth_views.LoginView.as_view(template_name='project/login.html'),name='login'),
	path('logout/',auth_views.LogoutView.as_view(),name='logout'),
	path('org/<pk>',views.OrganizationDetailView.as_view(),name='organization_detail'),
	path('partner/<pk>',views.PartnerProjectList.as_view(),name='partner_projects'),
	path('partner/<partner_id>/project/<project_id>',views.ProjectOverview.as_view(),name='project_overview'),
	path('partner/<partner_id>/project/<project_id>/video/<pk>',views.VideoDetailView.as_view(),name='video_detail'),
	path('partner/<partner_id>/project/<project_id>/video/add/',views.AwardFormView.as_view(),name='video_create'),
	path('partner/<partner_id>/project/add/',views.ProjectCreateView.as_view(),name='project_create'),
	path('partner/<partner_id>/project/<project_id>/video/<pk>/edit',views.VideoUpdateView.as_view(),name='video_edit'),
	path('partner/<partner_id>/project/<pk>/edit',views.ProjectUpdateView.as_view(),name='project_edit'),
	path('promotion/add',PromotionFormView.as_view(),name='promotion_add'),
	path('partner/<partner_id>/promotion/<pk>',PromotionDetailView.as_view(),name='promotion_detail'),
	path('get/type/<project_type>/project_id/<project_id>',views.get_project,name='get_project'),
	path('org/<org_id>/message_create',views.message_create,name='message_create'),
	path('org/<org_id>/message/<pk>',views.MessageDetailView.as_view(),name='message_detail'),
	path('org/<org_id>/awards-create',views.AwardsCreateView.as_view(),name='awards_create'),
	path('org/<org_id>/awards/<pk>',views.AwardsDetailView.as_view(),name='awards_detail'),
	path('org/<org_id>/awards/<pk>/edit',views.AwardsUpdateView.as_view(),name='awards_update'),
	path('org/<org_id>/awards/<awards_id>/award/add/',views.AwardFormView.as_view(),name='award_create'),
	path('org/<org_id>/awards/<awards_id>/award/<pk>',views.AwardDetailView.as_view(),name='award_detail'),
	path('org/<org_id>/awards/<awards_id>/award/<pk>/edit',views.AwardUpdateView.as_view(),name='award_edit'),
	path('password_change_done',views.password_change_done,name='password_change_done'),

	#path('org/<org_id>/awards/<awards_id>/award/<award_id>/upload/',views.FileUpload.as_view(),name='upload_form'),
	path('uploads/simple/', views.model_form_upload, name='simple_upload'),
	path('org/<org_id>/awards/<awards_id>/award/<award_id>/upload',views.test_upload,name='test_upload'),
	path('org/<org_id>/awards/<awards_id>/award/<award_id>/upload-files',views.upload_file,name='upload_file'),
	path('org/<org_id>/awards/<awards_id>/award/<award_id>/comment',views.comment_view,name='comment_view'),
	path('password-change',auth_views.PasswordChangeView.as_view(template_name='project/password_change_form.html'),name='password_change'),
	path('email',views.email,name='email'),
	path('comments-update',views.comments_update,name='comments-update'),
	path('approve-video/video/<video_id>',views.approve_video,name='approve_video'),
	]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/models.py
import hashlib, random, sys
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.fields import JSONField
from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.db import models
from . import constants
from O365 import Account
from picklefield.fields import PickledObjectField
import pandas as pd 
from pandas import DataFrame as df


# Create your models here.
from .googleDriveApi import GoogleDriveApi


class Organization(models.Model):
    name = models.CharField(max_length=200)
    logo = models.URLField(null=True,blank=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('project:organization_detail',kwargs={'pk':self.pk})
    @property
    def team(self):

        team_members = [t.user for t in Client.objects.filter(organization=self)] + [x for x in User.objects.filter(is_staff=True)]      

        #print(t.email for t in team_members)
        return team_members
    @property
    def team_email(self):
        team_members = [t.user for t in Client.objects.filter(organization=self)] + [x for x in User.objects.filter(is_staff=True)]        
        email_list = [t.email for t in list(team_members)]
        return email_list
    @property
    def videos(self):
        videos = Award.objects.filter(awards__organization=self)
        return videos
    @property
    def awards(self):
        return Awards.objects.filter(organization=self)

    @property
    def promotion(self):
        return Promotion.objects.filter(organization=self)
    @property
    def message(self):
        return Message.objects.filter(organization=self)
    @property
    def projects(self):
        return [a for a in self.awards if a.active==True] + [p for p in self.promotion] + [c for c in self.message]

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact_first = models.CharField(max_length=200)
    contact_last = models.CharField(max_length=200)
    contact_phone = models.CharField(max_length=200, blank=True, null=True)
    contact_email = models.EmailField()
    contact_role = models.CharField(max_length=200,blank=True,null=True,default='')
    partner_logo = models.URLField(max_length=2000, null=True, blank=True)
    organization = models.ForeignKey(Organization,on_delete=models.CASCADE,null=True,blank=True)
    def __str__(self):
        return self.user.username


    def get_absolute_url(self):
        return reverse('project:partner_projects', kwargs={'pk': self.pk})

    @property
    def awards(self):
        return Project.objects.filter(client=self)

    @property
    def promotion(self):
        return Promotion.objects.filter(client=self)
    @property
    def message(self):
        return Message.objects.filter(client=self)

    @property
    def projects(self):
        return [x for x in self.awards] + [y for y in self.promotion] + [z for z in self.message]
    @property
    def list_of_videos(self):

        return [x for x in Video.objects.filter(project__client=self)] + [y for y in self.message] + [z for z in self.promotion]




class Project(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    project_name = models.CharField(max_length=200)
    date = models.DateField()
    number_of_awards = models.PositiveSmallIntegerField()

    def __str__(self):
        return f"{self.client} {self.project_name} {self.date.year}"

    def get_absolute_url(self):
        return reverse('project:project_overview', kwargs={'partner_id': self.client.id, 'project_id': self.pk})

    @property
    def project_videos(self):
        return self.number_of_awards

    @property
    def type(self):
        return 'awards'


class Video(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    award_number = models.PositiveSmallIntegerField()
    award_name = models.CharField(max_length=200000)
    award_description = models.TextField()
    award_winner = models.CharField(max_length=2000)
    award_comments = models.TextField()
    award_assets = models.URLField(null=True, blank=True, default='#')
    script = models.URLField(null=True, blank=True, default='#')
    draft = models.URLField(null=True, blank=True, default='#')
    final_draft = models.URLField(null=True, blank=True, default='#')

    def __str__(self):
        return f"{self.project.client.user.username} {self.project.project_name} {str(self.award_number)} {self.award_name}"

    def get_absolute_url(self):
        return reverse('project:video_detail',
                       kwargs={'pk': self.pk, 'partner_id': self.project.client.id, 'project_id': self.project.id})

    @property
    def project_videos(self):
        return Project.objects.filter(client__id=self.project.id).count()


class Promotion(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    date = models.DateField(blank=True, null=True)
    name = models.CharField(max_length=500)
    logo = models.URLField(blank=True, null=True)
    theme = models.TextField(blank=True, null=True)
    attendees = models.PositiveSmallIntegerField(blank=True, null=True)
    exhibitors = models.PositiveSmallIntegerField(blank=True, null=True)
    venue = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=200, blank=True, null=True)
    target_audience = models.CharField(max_length=200, blank=True, null=True)
    feature_1 = models.TextField(blank=True, null=True)
    feature_2 = models.TextField(blank=True, null=True)
    feature_3 = models.TextField(blank=True, null=True)
    feature_4 = models.TextField(null=True,blank=True)
    feature_5 = models.TextField(null=True,blank=True)
    assets = models.URLField(null=True,blank=True)
    guests = models.CharField(max_length=200, null=True,blank=True)
    organization = models.ForeignKey(Organization,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return f"{self.client.user.username} {self.name}- {self.date}"

    @property
    def type(self):
        return 'promotion'

    def get_absolute_url(self):
        return reverse('project:promotion_detail', kwargs={'partner_id': self.client.id, 'pk': self.pk})

    @property
    def project_videos(self):
        return 1


class Message(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=2000, default="Client Message")
    date = models.DateField(null=True, blank=True)
    draft_script = models.URLField(null=True, blank=True)
    script = models.URLField(null=True, blank=True)
    assets = models.URLField(null=True, blank=True)
    draft = models.URLField(null=True, blank=True)
    final = models.URLField(null=True, blank=True)
    notes = JSONField(default=dict)
    organization = models.ForeignKey(Organization,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return f"Message {self.organization.name}"
    @property
    def type(self):
        return 'message'

    def get_absolute_url(self):
        return reverse('project:message_detail', kwargs={'partner_id': self.client.id, 'pk': self.pk})
class Awards(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    project_name = models.CharField(max_length=200)
    date = models.DateField()
    folder_id = models.CharField(max_length=100, null=True, blank=True)
    number_of_awards = models.PositiveSmallIntegerField()
    active = models.BooleanField(default=True)

    def get_object(self,queryset=None):
        obj = super(PostDetailView, self).get_object()
        if not obj.owner == self.request.user:
            print('you shall not pass')
        return obj

    def project_comments(self):
        all_comments = pd.concat([pd.concat([df([[x.award_number,x.award_name,x.award_project]],columns=['NUMBER','AWARD','PROJECT']),x.edit_comments],axis=1) for x in self.awards_list])
        return all_comments
    def __str__(self):
        return f"{self.organization.name} {self.project_name} {self.date.year}"

    def created_message(self):
        team_email = self.organization.team_email
        emaillist = list(set([team_email[0],team_email[1],team_email[2]]))
        subject = f"New Awards Project created for {self.organization.name}"
        html_content = '<h4>Thank you for adding 'f"{self.project_name}"' to the production portal. You can view all updates to this project and make any changes here: <a href="http://www.virtuous-circle.com/'f"org/{self.organization.id}/awards/{self.id}"'">'f"{self.project_name}"'</a></h4>'        
        text_content = f"Thank you for adding {self.project_name} to the production portal. You can view the progress and make changes to the project at http://www.virtuous-circle/org/{self.organization.id}/awards/{self.pk}"
        
        credentials=(settings.EMAIL_CLIENT,settings.EMAIL_SECRET)
        account = Account(credentials)
        message = account.new_message()
        message.subject = subject
        message.body = html_content
        message.to.add([emaillist])
        message.send()
        
        
    def get_absolute_url(self):
        return reverse('project:awards_detail', kwargs={'org_id': self.organization.id, 'pk': self.pk})
    @property
    def awards_list(self):
        return Award.objects.filter(awards=self).order_by('award_number','award_name')
    @property
    def project_videos(self):
        return self.number_of_awards

    @property
    def type(self):
        return 'awards'


@receiver(post_save, sender=Awards)
def update_awards(sender, instance, **kwargs):    
    #instance.created_message()       
    if instance.folder_id is None:

project/templates/project/awards_detail.html
{% extends 'project/base.html' %}
{% load extras %}
{% block content %}

<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <a href="{% url 'project:index' %}">
                            <img src="{{object.organization.logo}}" alt=""/>  
                            </a>      
                        </div>
                        <br>
                        <!--Button Items -->
                            <div class="profile-work">
                            <a class="btn btn-primary btn-block" href="{% url 'project:award_create' org_id=object.organization.id awards_id=object.id %}" role="button" data-toggle="popover" data-content="Add a new award video to project">Add Award</a>  
                            <a href="{% url 'project:awards_update' org_id=object.organization.id pk=object.pk %}" class="btn btn-primary btn-block">Edit Project</a>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="profile-head">
                        	<h5>{{object.project_name}}                </h5>
                            <h6>                                   {{object.date}}
                            </h6>
                            <h6>
                            Number of awards: 
                            {{object.number_of_awards}}
                            </h6>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#videos" role="tab" aria-controls="home" aria-selected="true">Videos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="home-tab" data-toggle="tab" href="#team" role="tab" aria-controls="home" aria-selected="true">Team</a>
                                </li>

                            </ul>
                        </div>
                        <!--Tab content-->
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="videos" role="tabpanel" aria-labelledby="home-tab">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Video</th>
                                            <th>Title</th>
                                            <th>Script</th>
                                            <th>Draft</th>
                                            <th>Final</th>
                                            <th>Complete</th>
                                        </tr>
                                        {% for v in object.awards_list %}
                                        <tr>
                                            <td><a href="{% url 'project:award_detail' org_id=v.awards.organization.id awards_id=v.awards.id pk=v.pk %}">{{v.award_number}}</a></td>
                                            <td><a href="{% url 'project:award_detail' org_id=v.awards.organization.id awards_id=v.awards.id pk=v.pk %}">{{v.award_name}}</a></td>
                                            {% if v.script is not None and v.draft != '#' %}
                                            <td style="text-align: center"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check2-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M15.354 2.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L8 9.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  <path fill-rule="evenodd" d="M1.5 13A1.5 1.5 0 0 0 3 14.5h10a1.5 1.5 0 0 0 1.5-1.5V8a.5.5 0 0 0-1 0v5a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 0 0-1H3A1.5 1.5 0 0 0 1.5 3v10z"/>
                                            </svg>                           
                                           </td>
                                           {% else %}
                                           <td></td>
                                           {% endif %}
                                           {% if v.draft is not None and v.draft != '#' %}
                                            <td style="text-align: center"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check2-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M15.354 2.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L8 9.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  <path fill-rule="evenodd" d="M1.5 13A1.5 1.5 0 0 0 3 14.5h10a1.5 1.5 0 0 0 1.5-1.5V8a.5.5 0 0 0-1 0v5a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 0 0-1H3A1.5 1.5 0 0 0 1.5 3v10z"/>
                                            </svg>                           
                                           </td>
                                           {% else %}
                                           <td></td>
                                           {% endif %}
                                           {% if v.final_draft is not None and v.final_draft != '#' %}
                                            <td style="text-align: center"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check2-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M15.354 2.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L8 9.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  <path fill-rule="evenodd" d="M1.5 13A1.5 1.5 0 0 0 3 14.5h10a1.5 1.5 0 0 0 1.5-1.5V8a.5.5 0 0 0-1 0v5a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 0 0-1H3A1.5 1.5 0 0 0 1.5 3v10z"/>
                                            </svg>                           
                                           </td>
                                           {% else %}
                                           <td></td>
                                           {% endif %}
                                           {% if v.complete == True %}
                                            <td style="text-align: center"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check2-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M15.354 2.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L8 9.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  <path fill-rule="evenodd" d="M1.5 13A1.5 1.5 0 0 0 3 14.5h10a1.5 1.5 0 0 0 1.5-1.5V8a.5.5 0 0 0-1 0v5a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 0 0-1H3A1.5 1.5 0 0 0 1.5 3v10z"/>
                                            </svg>                           
                                           </td>
                                           {% else %}
                                           <td></td>
                                           {% endif %}
                                        </tr>
                                        {% endfor %}
                                    </thead>
                                </table>                                      
                            </div>
                            <div class="tab-pane fade show" id="team" role="tabpanel" aria-labelledby="home-tab">
                                <div class="table-responsive">
                                    <table class="table table-bordered">        
                                        <thead>
                                            <tr>
                                                <th>Username</th>
                                                <th>First Name</th>
                                                <th>Last Name</th>
                                                <th>Role</th>                   
                                                <th>Email</th>
                                            </tr>                                   
                                        {% for t in object.organization.team %}
                                            <tr>
                                                <td>{{t.username}}</a></td>
                                                <td>{{t.first_name}}</td>
                                                <td>{{t.last_name}}</td>
                                                <td>{{t.role}}</td>
                                                <td>{{t.email}}</td>
                                            </tr>
                                    {% endfor %}
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
 
                </div>

                   
        </div>

{% endblock %}

project/templates/project/base.html
{% load static %}

{% load extras %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'project/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'project/css/animate.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'project/css/marg_pad.css' %}">
    <script src="{% static 'project/js/jquery-3.1.0.min.js' %}" type="text/javascript"></script>
<body>
<header>
    <div class="row">
        <div class="col-md-12">
            <div class="top_bar">
                <div class="container">
                    <nav>
                        <ul>                            
                            <li class="nav-item">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'project:index' %}">Home</a>
                {% else %}
                    <a href="">Home</a>
                    </li>
                {% endif %}
                            <li><a href="{% url 'project:logout' %}">Logout</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>

</header>
{% block content %}
{% endblock %}
<!-- Just an image -->


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

</html>
<script>
jQuery(document).ready(function () {
        jQuery('#datepicker').datepicker({
            format: 'dd-mm-yyyy',
            startDate: '+1d'
        });
    });
</script>

project/templates/project/file_form.html
<form method="post">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="submit">
</form>

project/templates/project/model_form_upload.html
{% extends 'project/base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="">Return to home</a></p>
{% endblock %}

project/templates/project/organization_detail.html
{% extends 'project/base.html' %}
{% load crispy_forms_tags %}
{% load extras %}

{% block content %}


<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <a href="{% url 'project:index' %}">
                            <img src="{{object.logo}}" alt=""/> </a>  
                        </div>
                        <!--Button items-->
                        <br>
                        <div class="profile-work">
							<a class="btn btn-primary btn-block" href="{% url 'project:awards_create' org_id=object.pk %}" role="button">New Awards Project</a>
							<a class="btn btn-primary btn-block" href="{% url 'project:message_create' org_id=object.pk %}" role="button">New Corporate Message</a>
							<a class="btn btn-primary btn-block" href="" role="button">New Promotion Project</a>
							<a class="btn btn-primary btn-block" href="#" role="button">New Feature Project</a>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="profile-head">
                           <h5>{{object.name}}</h5>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#team" role="tab" aria-controls="home" aria-selected="true">Team</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#projects" role="tab" aria-controls="profile" aria-selected="false">Projects</a>
                                </li>

                            </ul>
                        </div>
                        <!-- Tab Contnet -->
                                                <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="team" role="tabpanel" aria-labelledby="home-tab">
                            	<div class="table-responsive">
									<table class="table table-bordered">		
										<thead>
											<tr>
												<th>Username</th>
												<th>First Name</th>
												<th>Last Name</th>
												<th>Role</th>					
												<th>Email</th>
											</tr>									
									{% for t in object.team %}
											<tr>
												<td>{{t.username}}</a></td>
												<td>{{t.first_name}}</td>
												<td>{{t.last_name}}</td>
												<td>{{t.role}}</td>
												<td>{{t.email}}</td>
											</tr>
									{% endfor %}
										</thead>
									</table>
								</div>
                                      
                            </div>
                            <div class="tab-pane fade" id="projects" role="tabpanel" aria-labelledby="profile-tab">               	
 								<div class="table-responsive">
									<table class="table table-bordered">
										<thead>
											<tr>
												<th>Project</th>
												<th>Type</th>
												<th>Date</th>
												<th>Number of Videos</th>
											</tr>
											{% if object.pk != 1 %}
											{% for p in object.projects %}
											<tr>								
												<td><a href="{% url 'project:get_project' project_id=p.id project_type=p.type %}">{{p|name}}</a></td>
												<td>{{p.type}}</td>
												<td>{{p.date}}</td>
												<td>{{p.project_videos}}</td>
											</tr>
											{% endfor %}
											{% else %}
											{% for p in projects %}
											<tr>								
												<td><a href="{% url 'project:get_project' project_id=p.id project_type=p.type %}">{{p|name}}</a></td>
												<td>{{p.type}}</td>
												<td>{{p.date}}</td>
												<td>{{p.project_videos}}</td>
											</tr>
											{% endfor %}
											{% endif %}
										</thead>
									</table>
								</div>
								</div>     

                            </div>
                        </div>
                    </div>
                </div>           
</div>

{% endblock %}